language: python

dist: xenial

branches:
  only:
    - master

python:
  - "2.7"
  - "3.7"

install:
  - pip install coveralls
  - pip install geventhttpclient
  - pip install -e .[test]

script:
  - python setup.py test


after_success:
  - if [[ $TRAVIS_BRANCH == 'master' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then coveralls; fi;
